### ISSUE TITLE
to device issue

### ISSUE THREAD

**Issue by blackbin7** [smthemex/ComfyUI_CSGO_Wrapper#4]
I'm encountering this issue like PyTorch is attempting to move a module from the 'meta' device (an uninitialized state) to another device without properly initializing it first. Do you have any idea of how to solve this issue? Much thanks!
```

got prompt
Loading pipeline components...:   0%|                                                                                                                                                | 0/7 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel: 
 ['text_model.embeddings.position_ids']
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  6.00it/s]
Loading pipeline components...:   0%|                                                                                                                                                | 0/7 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel: 
 ['text_model.embeddings.position_ids']
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 18.59it/s]
!!! Exception during processing !!! Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
Traceback (most recent call last):
  File "/data3/home/bzhang/comfyui-space/creative_fusion/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data3/home/bzhang/comfyui-space/creative_fusion/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data3/home/bzhang/comfyui-space/creative_fusion/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/data3/home/bzhang/comfyui-space/creative_fusion/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/data3/home/bzhang/comfyui-space/creative_fusion/custom_nodes/ComfyUI_CSGO_Wrapper/csgo_node.py", line 176, in test
    csgo = CSGO(pipe, img_encoder, csgo_ckpt, device, image_encoder_config,num_content_tokens=num_content_tokens, num_style_tokens=num_style_tokens,
  File "/data3/home/bzhang/comfyui-space/creative_fusion/custom_nodes/ComfyUI_CSGO_Wrapper/CSGO/ip_adapter/ip_adapter.py", line 282, in __init__
    self.pipe = sd_pipe.to(self.device)
  File "/opt/conda/envs/CSGO/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 431, in to
    module.to(device, dtype)
  File "/opt/conda/envs/CSGO/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/opt/conda/envs/CSGO/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/opt/conda/envs/CSGO/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/opt/conda/envs/CSGO/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/opt/conda/envs/CSGO/lib/python3.9/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/CSGO/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1167, in convert
    raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

Prompt executed in 22.80 seconds

```

**Comment by smthemex** [comment]
I have encountered a similar problem before, mainly that the csgo.bin model does not match (when your token is set to default 4, 32). Changing to csgo_4_32.bin can solve the problem.
If the above switch cannot be resolved, it is also possible that the IP adapter model does not match. You should choose "model.safensors" under the image encoder of SDXL. I suggest you rename it because too many models are named this way.
